apiVersion: v1
kind: Service
metadata:
  name: api-dotnet-service
spec:
  type: NodePort
  selector:
    app: api-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Acesso externo via <ip-do-node>:30080
