apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  Jwt__Key: bXktc3VwZXItc2VjcmV0LWs=   # (base64 de 'my-super-secret-k')
  Jwt__Issuer: YXBpLm15ZG9tYWluLmNvbQ== # (base64 de 'api.mydomain.com')
