apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-dotnet
  template:
    metadata:
      labels:
        app: api-dotnet
    spec:
      containers:
      - name: api-dotnet
        image: seuusuario/seuprojeto:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ConnectionStrings__DefaultConnection
        - name: FeatureFlag__EnableX
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: FeatureFlag__EnableX
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: Jwt__Key
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: Jwt__Issuer
